### ISSUE TITLE
Dosen't seem to work anymore.

### ISSUE THREAD

**Issue by jbunikis** [narsimplyme/SynoDM-dlm-for-nyaa#1]
Installed on DS3617xs  version 3,2,3-25426 v.3.
When using search it get message "No match found".

**Comment by narsimplyme** [comment]
Both DLM work for me.
I'm using DS220j with 7.0-41890
Please confirm that you can access
[https://nyaa.si/?page=rss&term=](https://nyaa.si/?page=rss&term=)
[https://sukebei.nyaa.si/?page=rss&term=](https://sukebei.nyaa.si/?page=rss&term=)

If you can access both links, please test some keywords after the "term=" and see if there are results
I've tested right now and the download works just fine for me

**Comment by jbunikis** [comment]
"https://nyaa.si/?page=rss&term="
and
"https://sukebei.nyaa.si/?page=rss&term="
Loads fine and shows site in xml code.
 
Adding "shield" or "slime" -> "https://sukebei.nyaa.si/?page=rss&term=shield"
Gives this 
"Elasticsearch has encountered an error: ConnectionTimeout caused by - ReadTimeoutError(HTTPConnectionPool(host='localhost', port=9200): Read timed out. (read timeout=10))"

Edit:
So i tried the links again and they do seem to work sometimes. I've no idea why that might. 
In Synology it still doesn't find any torrents when using.

![Screenshot_2](https://user-images.githubusercontent.com/45873795/138730816-8ed7c599-bf74-4b1a-9195-c7b9f60700e5.png)
![Screenshot_3](https://user-images.githubusercontent.com/45873795/138730835-b88ff101-e1ee-4f12-a595-d665628b4e22.png)

Am I doing something wrong?
